// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalWebsite.Services;

namespace PersonalWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190218033458_AddDateTimeToLogs")]
    partial class AddDateTimeToLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonalWebsite.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndTime");

                    b.Property<int>("EventType");

                    b.Property<string>("Header2");

                    b.Property<string>("Header3");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Currently in the computer science program at ETSU. Minoring with a mathematics minor. Graduating in May 2019.",
                            EndTime = new DateTime(2019, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 0,
                            Header2 = "East Tennessee State University",
                            Header3 = "Computer Science B.S.",
                            StartTime = new DateTime(2015, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Primarily responsible to change the website server from an outdated Windows 2003 server to a Windows 2012 Server. Worked with another intern to write SQL code that would transfer the data dynamically, such code included cursor for loops.",
                            EndTime = new DateTime(2016, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 1,
                            Header2 = "Holston Medical Group",
                            Header3 = "Software Developer Intern",
                            StartTime = new DateTime(2016, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "At NFS, I worked on the software used in the plant. Mostly working with ASP.Net MVC, C#.NET, SQL.",
                            EndTime = new DateTime(2019, 2, 17, 22, 34, 57, 800, DateTimeKind.Local).AddTicks(592),
                            EventType = 1,
                            Header2 = "Nuclear Fuel Services",
                            Header3 = "IT Application Intern",
                            StartTime = new DateTime(2017, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PersonalWebsite.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action");

                    b.Property<string>("IPAddress");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("PersonalWebsite.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BreifDescription");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreifDescription = "I foresaw an easier way to process employee pay checks at the small business I work at. Instead of calculating the tax by hand, I created a program that allows one to input the name, amount of hours worked, and the pay rate for an employee. Then the program will display a window with the employee's name, gross pay, social security tax, medicare tax, federal withhold tax and net pay. The program will then ask if the user would like to process another employee.",
                            Description = "",
                            Name = "Employee Pay Stub Calculator",
                            URL = "https://github.com/feathersct"
                        },
                        new
                        {
                            Id = 2,
                            BreifDescription = "This program will split a text file into paragraphs, sentences, words, and tokens. It will then display those values to you. You can also flip through each paragraph or sentence and see the average word count, sentence count, etc.",
                            Description = "",
                            Name = "Text Analysis",
                            URL = "https://github.com/feathersct/Text-Analysis"
                        },
                        new
                        {
                            Id = 3,
                            BreifDescription = "This project started as an idea to control my lights without messing with the wires or replacing the light switch. This idea would primarily be for my college dorm room or apartment. This projects brain is a raspberry pi 3 with an Apache server in order to be located on the network. Also, the webpage was implemented with HTML, CSS, JavaScript, which would communicate to a PHP file which would access the Python script to control the servo motor and turn the light switch ON or OFF.",
                            Description = "This project started as an idea that if I was laying in my bed and didn't want to get up and turn the lights off that I can turn them off through my phone. First, in order to control the light switch I would have a raspberry pi hooked up to a servo motor and with some 3D parts the lights would be flicked on or off. In order to control the raspberry pi with my phone, I needed to install an Apache server so it can host the website I would make for the actual remote to flick the light on and off. After installing Apache the next step is to make the website. I used HTML/CSS/JS as the front end and used PHP as the back end. The front end would have buttons labeled \"on\" and \"off\". When pressed the button would activate the php file sending its title in return would call a Python script to turn the light on or off.",
                            Name = "Light Switch Project"
                        },
                        new
                        {
                            Id = 4,
                            BreifDescription = "This was my first portfolio website I built in 2016. It's a simple one-pager like this one. Since then, I think my web development and design skills have expanded immensely.",
                            Description = "",
                            Name = "Old Website",
                            URL = "https://feathersct.github.io/Clayton-Feathers/Index3.html"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
